backend/source/products_prices/accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

backend/source/products_prices/products/urls.py
from django.urls import path

from .views import (
    BackOfficeView,
    CalculatePriceView,
    ProductsListView,
    list_calculated_prices,
)

app_name = "products"

urlpatterns = [
    path(
        "",
        ProductsListView.as_view(template_name="products/products_list.html"),
        name="home",
    ),
    path("calculate/", CalculatePriceView.as_view(), name="calculate"),
    path("list_calculated", list_calculated_prices, name="list_calculated"),
    path("backend/", BackOfficeView.as_view(), name="backoffice"),
]

backend/source/products_prices/products_prices/urls.py
"""
URL configuration for products_prices project.

"""

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import (
    TemplateView,
)  # Initial project landing page. To be removed

urlpatterns = [
    # path('', TemplateView.as_view(template_name="startup.html"), name="home"),
    path("", include("products.urls", namespace="products")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

backend/source/products_prices/accounts/models.py
from django.db import models

# Create your models here.

backend/source/products_prices/products/models.py
from django.contrib.auth.models import User
from django.db import models


class BaseModel(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User, related_name="author", on_delete=models.CASCADE, null=True, blank=True
    )
    last_modified_by = models.ForeignKey(
        User, related_name="editor", on_delete=models.CASCADE, null=True, blank=True
    )


class Product(BaseModel):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

backend/source/products_prices/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

backend/source/products_prices/products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.shortcuts import render
from django.views.generic import ListView, View

from .models import Product


class ProductsListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "products/products_list.html"
    context_object_name = "products"


class BackOfficeView(LoginRequiredMixin, View):
    def get(self, request):
        template_name = "products/back_office.html"
        return render(request, template_name=template_name)


class CalculatePriceView(LoginRequiredMixin, View):
    template_name = "products/calculated_prices.html"

    def post(self, request):
        products_to_price = [int(p) for p in request.POST["products_list"].split(",")]

        products = Product.objects.filter(pk__in=products_to_price)
        products_total = products.aggregate(Sum("price"))

        context = {
            "key": "Value",
            "products": products,
            "products_total": products_total["price__sum"],
        }
        return render(request, template_name=self.template_name, context=context)


def list_calculated_prices(request):
    # import pdb; pdb.set_trace()
    template_name = "products/calculated_prices.html"
    context = {"key": "Value"}
    # return HttpResponseRedirect('/')
    return render(request, template_name=template_name, context=context)

backend/source/products_prices/products/templates/products/back_office.html
{% extends 'base.html' %}

 {% block content %}
    <section class="container text-center">
        <article class="m-4">
            Place-holder for Products CRUD back-office.
        </article>
        <article class="text-center hs-6 text m-4">
            Once Django Admin should not be used by users interactions.
        </article>
    </section>
 {% endblock content %}

backend/source/products_prices/products/templates/products/calculated_prices.html
{% extends 'base.html' %}

 {% block content %}
    <h1>Products Calculated Prices</h1>

<section class="m-auto p-2 container-lg border border-1">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Name</th>
              <th scope="col">Price</th>
<!--              <th scope="col">Description</th>-->
<!--              <th scope="col">Qtd</th>-->
            </tr>
          </thead>
          <tbody>
            {% for product in products %}
                <tr>
                  <th scope="row">{{product.id}}</th>
                  <td>{{ product.name }}</td>
                  <td>{{ product.price }}</td>
                  <td>
<!--                      <a-->
<!--                          class="btn btn-primary" data-bs-toggle="collapse"-->
<!--                          href="#product_description_{{product.id}}"-->
<!--                          role="button" aria-expanded="false"-->
<!--                          aria-controls="product_description_{{product.id}}"-->
<!--                          id="btn_show_product_description_{{product.id}}"-->
<!--                          onclick="toggleLabel('btn_show_product_description_{{product.id}}')"-->
<!--                      >-->
<!--                        Show-->
<!--                      </a>-->
<!--                    <div class="collapse" id="product_description_{{product.id}}">-->
<!--                      <div class="card card-body">-->
<!--                        {{ product.description }}-->
<!--                      </div>-->
<!--                    </div>-->
                  </td>
<!--                  <td>-->
<!--                    <input class="border-1" type="checkbox" name="products_selection" id="select_product_{{product.id}}" autocomplete="off" >-->
<!--                  </td>-->
                </tr>
            {% endfor %}
          </tbody>
        </table>
        <aside>
        Total of selected products: {{products_total}}
        </aside>
    </section>
    <aside class="m-2">
        <div class="text-center">
            <a href="/">
                <button
                    type="button"
                    data-mdb-button-init data-mdb-ripple-init class="btn btn-primary  m-auto">
                    Home
                </button>
            </a>
        </div>

    </aside>
{% endblock content %}

backend/source/products_prices/products/templates/products/components/product_list_instructions.html
<aside class="p-2">
    <button
        type="button"
        class="btn btn-success m-2"
        onclick="calculateTotal()"
    >
        Calculate
    </button>
    <details class="card card-body">
        Please select the products you want to calculate the total price, and click the 'Calculate' button.
    </details>
</aside>

backend/source/products_prices/products/templates/products/home.html
{% extends 'products_prices/base.html' %}

 {% block content %}
    <h1>Sample data</h1>


    {% if user.is_authenticated %}
        <p>
            Hi {{ user.username }}!
        </p>
        <p>
            <a href="{% url 'posts:backoffice' %}">BackOffice</a>
        </p>
        <p>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Log Out</button>
            </form>
        </p>
    {% else %}
        <p>You are not logged in</p>
            <a href="{% url 'login' %}">Log In</a>
        {% endif %}


 {% endblock content %}

backend/source/products_prices/products/templates/products/products_list.html
{% extends 'base.html' %}

 {% block content %}
    <h1>Products list</h1>
    <aside class="m-2 m-auto w-75 d-none" id="modal_alert_no_products_selected" role="button" data-toggle="tooltip" data-placement="top" title="Dismiss">
        <div class="alert alert-danger " role="alert" onclick="hide_modal('modal_alert_no_products_selected')">
            Please select products to calculate.
        </div>
    </aside>
    <section class="m-auto p-2 container-lg border border-1 shadow">
        {% include 'products/components/product_list_instructions.html' %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Name</th>
              <th scope="col">Price</th>
              <th scope="col">Description</th>
              <th scope="col">Select</th>
            </tr>
          </thead>
          <tbody>
            {% for product in products %}
                <tr>
                  <th scope="row">{{product.id}}</th>
                  <td>{{ product.name }}</td>
                  <td>{{ product.price }}</td>
                  <td>
                      <a
                          class="btn btn-primary" data-bs-toggle="collapse"
                          href="#product_description_{{product.id}}"
                          role="button" aria-expanded="false"
                          aria-controls="product_description_{{product.id}}"
                          id="btn_show_product_description_{{product.id}}"
                          onclick="toggleLabel('btn_show_product_description_{{product.id}}')"
                      >
                        Show
                      </a>
                    <div class="collapse" id="product_description_{{product.id}}">
                      <div class="card card-body">
                        {{ product.description }}
                      </div>
                    </div>
                  </td>
                  <td>
                    <input class="border-1" type="checkbox" name="products_selection" id="select_product_{{product.id}}" autocomplete="off" >
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
        {% include 'products/components/product_list_instructions.html' %}
    </section>
<!--    Form to submit the list of selected values-->
    <form action="/calculate/" method="post" class="d-none" id="send_values">
        <input type="hidden" name="products_list" value="" />
        {% csrf_token %}
    </form>
{% endblock content %}

{% block local_scripts %}
    <script>
        function toggleLabel(id) {
            const btn = document.getElementById(`${id}`)
            const btn_text = btn.text.trim()
            if(btn_text === 'Show') {
                btn.innerHTML = 'Hide'
            } else {
                btn.innerHTML = 'Show'
            }
        }

        function calculateTotal(){
            // Get selected products from displayed list
            const selected_products = document.querySelectorAll('input[name=products_selection]:checked');
            let selected_products_list = []

            selected_products.forEach((product) => {
                selected_products_list.push(parseInt(product.parentElement.parentElement.children[0].textContent))
            })
            console.log(selected_products_list)
            if(selected_products_list.length === 0){
                document.getElementById('modal_alert_no_products_selected').classList.remove('d-none')
                return
            }
            const send_form = document.getElementById('send_values')
            // Assign values to field
            send_form.firstElementChild.value = selected_products_list
            send_form.submit()
        }
        function hide_modal(modal_id) {
            document.getElementById(modal_id).classList.add('d-none')
        }
    </script>
{% endblock local_scripts %}

backend/source/products_prices/templates/products_prices/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BI - Pricing Calculation |{% block title %} Home {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body class="p-4">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Products Prices</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
      </ul>
        <span class="d-flex mb-3">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item p-2">
            {% if user.is_authenticated %}
            Hi {{ user.username }}!
            </li>
            <li class="nav-item p-2">
                <a class="no-decorations" href="{% url 'products:backoffice' %}">BackOffice</a>
              </li>
            <li class="nav-item p-2">
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="button submit">Log Out</button>
                </form>
            </li>
                </ul>
          {% else %}
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </span>
    </div>
  </div>
</nav>

    {% block content %}
    {% endblock content %}
    {% block local_scripts %}
    {% endblock local_scripts %}
    <hr>
    <footer class="text-center fs-6 text small">
            © Copyright {{ current_year }} | Running on: [{{ active_branch }}] - v 0.0.8
    </footer>
</body>
</html>

backend/source/products_prices/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login form</title>
</head>
<body>
    Registration login
</body>
</html>

backend/source/products_prices/templates/startup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Startup Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<!--
 Source: https://getbootstrap.com/docs/5.0/examples/jumbotron/
  -->
<body>
   <main>
  <div class="container py-4">

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Project landing page</h1>
        <p class="col-md-8 fs-4">We are building your project.</p>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2024
    </footer>
  </div>
</main>

</body>
</html>